In [4]:
import pandas as pd

In [5]:
deliveries = pd.read_csv("/Users/prashantmaurya/Desktop/ipl/IPL_ball_by_ball_updated.csv")

In [6]:
deliveries.head()

,match_id,season,start_date,venue,innings,ball,batting_team,bowling_team,striker,non_striker,...,extras,wides,noballs,byes,legbyes,penalty,wicket_type,player_dismissed,other_wicket_type,other_player_dismissed
0,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.1,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,BB McCullum,...,1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.2,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.3,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.4,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,335982,2008,2008-04-18,M Chinnaswamy Stadium,1,0.5,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,SC Ganguly,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
deliveries.columns

Index(['match_id', 'season', 'start_date', 'venue', 'innings', 'ball',
       'batting_team', 'bowling_team', 'striker', 'non_striker', 'bowler',
       'runs_off_bat', 'extras', 'wides', 'noballs', 'byes', 'legbyes',
       'penalty', 'wicket_type', 'player_dismissed', 'other_wicket_type',
       'other_player_dismissed'],
      dtype='object')

In [8]:
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243815 entries, 0 to 243814
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   match_id                243815 non-null  int64
 1   season                  243815 non-null  int64
 2   start_date              243815 non-null  object
 3   venue                   243815 non-null  object
 4   innings                 243815 non-null  int64
 5   ball                    243815 non-null  float64
 6   batting_team            243815 non-null  object
 7   bowling_team            243815 non-null  object
 8   striker                 243815 non-null  object
 9   non_striker             243815 non-null  object
 10  bowler                  243815 non-null  object
 11  runs_off_bat            243815 non-null  int64
 12  extras                  243815 non-null  int64
 13  wides                   7652 non-null    float64
 14  noballs                 1018 non-null    float64
 15  byes                    628 non-null     float64
 16  legbyes                 3778 non-null    float64
 17  penalty                 2 non-null       float64
 18  wicket_type             12067 non-null   object
 19  player_dismissed        12067 non-null   object
 20  other_wicket_type       0 non-null       float64
 21  other_player_dismissed  0 non-null       float64
dtypes: float64(8), int64(5), object(9)
memory usage: 40.9+ MB

In [9]:
deliveries[['wides', 'noballs', 'byes', 'legbyes', 'penalty']] = deliveries[
    ['wides', 'noballs', 'byes', 'legbyes', 'penalty']
].fillna(0)

In [10]:
deliveries.isnull().sum()

match_id                       0
season                         0
start_date                     0
venue                          0
innings                        0
ball                           0
batting_team                   0
bowling_team                   0
striker                        0
non_striker                    0
bowler                         0
runs_off_bat                   0
extras                         0
wides                          0
noballs                        0
byes                           0
legbyes                        0
penalty                        0
wicket_type               231748
player_dismissed          231748
other_wicket_type         243815
other_player_dismissed    243815
dtype: int64

In [11]:
deliveries['is_wicket'] = deliveries['player_dismissed'].notnull().astype(int)

In [12]:
deliveries[['player_dismissed', 'is_wicket']].head(10)

  player_dismissed  is_wicket
0              NaN          0
1              NaN          0
2              NaN          0
3              NaN          0
4              NaN          0
5              NaN          0
6              NaN          0
7              NaN          0
8              NaN          0
9              NaN          0

Total Batters Career Runs Stat

In [13]:
runs = deliveries.groupby('striker')['runs_off_bat'].sum()

In [14]:
runs

striker
A Ashish Reddy     280
A Badoni           399
A Chandila           4
A Chopra            53
A Choudhary         25
                  ...
Yashpal Singh       47
Younis Khan          3
Yudhvir Singh        1
Yuvraj Singh      2754
Z Khan             117
Name: runs_off_bat, Length: 637, dtype: int64

In [15]:
balls = deliveries[
    deliveries['wides']==0
].groupby('striker').size()

In [16]:
balls

striker
A Ashish Reddy     193
A Badoni           302
A Chandila           7
A Chopra            71
A Choudhary         20
                  ...
Yashpal Singh       66
Younis Khan          7
Yudhvir Singh        2
Yuvraj Singh      2122
Z Khan             141
Length: 637, dtype: int64

In [17]:
fours = deliveries[
    deliveries['runs_off_bat']==4
].groupby('striker').size()

In [18]:
fours

striker
A Ashish Reddy     16
A Badoni           24
A Chopra            7
A Choudhary         1
A Flintoff          5
                 ...
YV Dhull            1
YV Takawale        26
Yashpal Singh       5
Yuvraj Singh      218
Z Khan             11
Length: 516, dtype: int64

In [19]:
sixes = deliveries[
    deliveries['runs_off_bat']==6
].groupby('striker').size()

In [20]:
sixes

striker
A Ashish Reddy     15
A Badoni           19
A Choudhary         1
A Flintoff          2
A Manohar          10
                 ...
YBK Jaiswal        48
YK Pathan         161
YV Takawale         3
Yuvraj Singh      149
Z Khan              2
Length: 427, dtype: int64

In [21]:
dot_balls = deliveries[
    (deliveries['runs_off_bat']==0)
    & (deliveries['wides']==0)
].groupby('striker').size()

In [22]:
dot_balls

striker
A Ashish Reddy     58
A Badoni          104
A Chandila          3
A Chopra           41
A Choudhary         4
                 ...
Yashpal Singh      38
Younis Khan         4
Yudhvir Singh       1
Yuvraj Singh      892
Z Khan             74
Length: 630, dtype: int64

In [23]:
dismissals = deliveries[
    deliveries['player_dismissed'].notna()
]

dismissals = dismissals.groupby(
    'player_dismissed'
).size()

In [24]:
dismissals

player_dismissed
A Ashish Reddy     15
A Badoni           18
A Chopra            6
A Choudhary         1
A Flintoff          2
                 ...
Yashpal Singh       4
Younis Khan         1
Yudhvir Singh       2
Yuvraj Singh      111
Z Khan             14
Length: 602, dtype: int64

In [25]:
batter_stats = pd.concat(
    [
        runs,
        balls,
        fours,
        sixes,
        dot_balls,
        dismissals
    ],
    axis=1
)

In [26]:
batter_stats.columns = [
    'runs',
    'balls',
    '4s',
    '6s',
    'dot_balls',
    'outs'
]

In [27]:
batter_stats = batter_stats.fillna(0)

In [28]:
batter_stats

                  runs   balls     4s     6s  dot_balls   outs
A Ashish Reddy   280.0   193.0   16.0   15.0       58.0   15.0
A Badoni         399.0   302.0   24.0   19.0      104.0   18.0
A Chandila         4.0     7.0    0.0    0.0        3.0    0.0
A Chopra          53.0    71.0    7.0    0.0       41.0    6.0
A Choudhary       25.0    20.0    1.0    1.0        4.0    1.0
...                ...     ...    ...    ...        ...    ...
Younis Khan        3.0     7.0    0.0    0.0        4.0    1.0
Yudhvir Singh      1.0     2.0    0.0    0.0        1.0    2.0
Yuvraj Singh    2754.0  2122.0  218.0  149.0      892.0  111.0
Z Khan           117.0   141.0   11.0    2.0       74.0   14.0
A Nel              0.0     0.0    0.0    0.0        0.0    1.0

[638 rows x 6 columns]

In [29]:
batter_stats['SR']=(
    batter_stats['runs']
    /batter_stats['balls']
)*100

In [30]:
batter_stats['average']=(
    batter_stats['runs']
    /batter_stats['outs']
)

In [31]:
batter_stats = batter_stats.sort_values(
    by='runs',
    ascending=False
)

In [32]:
batter_stats = batter_stats.fillna(0)

batter_stats['runs']=batter_stats['runs'].astype(int)
batter_stats['balls']=batter_stats['balls'].astype(int)
batter_stats['4s']=batter_stats['4s'].astype(int)
batter_stats['6s']=batter_stats['6s'].astype(int)
batter_stats['dot_balls']=batter_stats['dot_balls'].astype(int)
batter_stats['outs']=batter_stats['outs'].astype(int)

batter_stats['SR']=round(
    batter_stats['SR'],2
)

batter_stats['average']=round(
    batter_stats['average'],2
)

In [33]:
batter_stats.head(10)

                runs  balls   4s   6s  dot_balls  outs      SR  average
V Kohli         7273   5590  646  235       1883   195  130.11    37.30
S Dhawan        6617   5205  750  149       1929   188  127.13    35.20
DA Warner       6399   4577  646  226       1665   156  139.81    41.02
RG Sharma       6213   4779  554  258       1789   210  130.01    29.59
SK Raina        5536   4046  506  204       1345   171  136.83    32.37
AB de Villiers  5181   3411  414  253       1039   130  151.89    39.85
MS Dhoni        5082   3739  349  239       1266   131  135.92    38.79
CH Gayle        4997   3346  408  359       1466   126  149.34    39.66
RV Uthappa      4954   3801  481  182       1472   180  130.33    27.52
KD Karthik      4517   3406  439  139       1172   175  132.62    25.81

YearWise Stats of Batters

In [34]:
runs = deliveries.groupby(
    ['season','striker']
)['runs_off_bat'].sum()

In [35]:
balls = deliveries[
    deliveries['wides']==0
].groupby(
    ['season','striker']
).size()

In [36]:
fours = deliveries[
    deliveries['runs_off_bat']==4
].groupby(
    ['season','striker']
).size()

In [37]:
sixes = deliveries[
    deliveries['runs_off_bat']==6
].groupby(
    ['season','striker']
).size()

In [38]:
dot_balls = deliveries[
    (deliveries['runs_off_bat']==0)
    &
    (deliveries['wides']==0)
].groupby(
    ['season','striker']
).size()

In [39]:
outs = deliveries[
    deliveries['player_dismissed'].notna()
]

outs = outs.groupby(
    ['season','player_dismissed']
).size()

In [40]:
season_batter_stats = pd.concat(
    [
        runs,
        balls,
        fours,
        sixes,
        dot_balls,
        outs
    ],
    axis=1
)

In [41]:
season_batter_stats.columns=[
    'runs',
    'balls',
    '4s',
    '6s',
    'dot_balls',
    'outs'
]

In [42]:
season_batter_stats=season_batter_stats.fillna(0)

In [43]:
season_batter_stats['SR']=round(
(
season_batter_stats['runs']
/
season_batter_stats['balls']
)*100,2)

In [44]:
season_batter_stats['average']=round(
season_batter_stats['runs']
/
season_batter_stats['outs']
,2)

In [45]:
season_batter_stats=season_batter_stats.reset_index()

In [46]:
season_batter_stats=season_batter_stats.sort_values(
by=['season','runs'],
ascending=[False,False]
)

In [47]:
season_batter_stats.columns

Index(['season', 'level_1', 'runs', 'balls', '4s', '6s', 'dot_balls', 'outs',
       'SR', 'average'],
      dtype='object')

In [48]:
season_batter_stats.rename(
    columns={'level_1':'striker'},
    inplace=True
)

In [49]:
season_batter_stats.columns

Index(['season', 'striker', 'runs', 'balls', '4s', '6s', 'dot_balls', 'outs',
       'SR', 'average'],
      dtype='object')

In [50]:
season_batter_stats[
    season_batter_stats['striker']=="V Kohli"
].reset_index(drop=True)

,season,striker,runs,balls,4s,6s,dot_balls,outs,SR,average
0,2023,V Kohli,639.0,457.0,65.0,16.0,130.0,12.0,139.82,53.25
1,2022,V Kohli,341.0,294.0,32.0,8.0,115.0,15.0,115.99,22.73
2,2021,V Kohli,405.0,339.0,43.0,9.0,126.0,14.0,119.47,28.93
3,2020,V Kohli,471.0,386.0,24.0,11.0,100.0,11.0,122.02,42.82
4,2019,V Kohli,464.0,328.0,46.0,13.0,93.0,14.0,141.46,33.14
5,2018,V Kohli,530.0,381.0,52.0,18.0,121.0,11.0,139.11,48.18
6,2017,V Kohli,308.0,252.0,23.0,11.0,90.0,10.0,122.22,30.80
7,2016,V Kohli,973.0,640.0,84.0,38.0,169.0,12.0,152.03,81.08
8,2015,V Kohli,505.0,386.0,35.0,23.0,139.0,11.0,130.83,45.91
9,2014,V Kohli,359.0,294.0,23.0,16.0,107.0,13.0,122.11,27.62
10,2013,V Kohli,639.0,459.0,65.0,22.0,164.0,14.0,139.22,45.64
11,2012,V Kohli,364.0,326.0,33.0,10.0,129.0,13.0,111.66,28.00
12,2011,V Kohli,557.0,460.0,55.0,16.0,180.0,12.0,121.09,46.42
13,2010,V Kohli,307.0,212.0,26.0,12.0,57.0,11.0,144.81,27.91
14,2009,V Kohli,246.0,219.0,22.0,8.0,92.0,11.0,112.33,22.36
15,2008,V Kohli,165.0,157.0,18.0,4.0,71.0,11.0,105.10,15.00

In [51]:
season_batter_stats[
season_batter_stats['striker']=="V Kohli"
]

,season,striker,runs,balls,4s,6s,dot_balls,outs,SR,average
2433,2023,V Kohli,639.0,457.0,65.0,16.0,130.0,12.0,139.82,53.25
2260,2022,V Kohli,341.0,294.0,32.0,8.0,115.0,15.0,115.99,22.73
2087,2021,V Kohli,405.0,339.0,43.0,9.0,126.0,14.0,119.47,28.93
1939,2020,V Kohli,471.0,386.0,24.0,11.0,100.0,11.0,122.02,42.82
1804,2019,V Kohli,464.0,328.0,46.0,13.0,93.0,14.0,141.46,33.14
1662,2018,V Kohli,530.0,381.0,52.0,18.0,121.0,11.0,139.11,48.18
1521,2017,V Kohli,308.0,252.0,23.0,11.0,90.0,10.0,122.22,30.80
1383,2016,V Kohli,973.0,640.0,84.0,38.0,169.0,12.0,152.03,81.08
1245,2015,V Kohli,505.0,386.0,35.0,23.0,139.0,11.0,130.83,45.91
1110,2014,V Kohli,359.0,294.0,23.0,16.0,107.0,13.0,122.11,27.62
983,2013,V Kohli,639.0,459.0,65.0,22.0,164.0,14.0,139.22,45.64
808,2012,V Kohli,364.0,326.0,33.0,10.0,129.0,13.0,111.66,28.00
636,2011,V Kohli,557.0,460.0,55.0,16.0,180.0,12.0,121.09,46.42
456,2010,V Kohli,307.0,212.0,26.0,12.0,57.0,11.0,144.81,27.91
290,2009,V Kohli,246.0,219.0,22.0,8.0,92.0,11.0,112.33,22.36
138,2008,V Kohli,165.0,157.0,18.0,4.0,71.0,11.0,105.10,15.00

Match Wise Batters Stats

In [52]:
match_runs = deliveries.groupby(
    ['match_id','striker']
)['runs_off_bat'].sum().reset_index(name='runs')

In [53]:
match_balls = deliveries[
    deliveries['wides']==0
].groupby(
    ['match_id','striker']
).size().reset_index(name='balls')

In [54]:
match_fours = deliveries[
    deliveries['runs_off_bat']==4
].groupby(
    ['match_id','striker']
).size().reset_index(name='4s')

In [55]:
match_sixes = deliveries[
    deliveries['runs_off_bat']==6
].groupby(
    ['match_id','striker']
).size().reset_index(name='6s')

In [56]:
match_batter_stats = match_runs

for df in [match_balls,match_fours,match_sixes]:
    
    match_batter_stats=match_batter_stats.merge(
        df,
        on=['match_id','striker'],
        how='left'
    )

In [57]:
match_batter_stats=match_batter_stats.fillna(0)

In [58]:
match_batter_stats['SR']=round(
(
match_batter_stats['runs']
/
match_batter_stats['balls']
)*100,2)

In [59]:
match_batter_stats[
match_batter_stats['striker']=="V Kohli"
].sort_values(
by='runs',
ascending=False
).head()

       match_id  striker  runs  balls    4s   6s      SR
8448     980999  V Kohli   113   50.0  12.0  8.0  226.00
8373     980987  V Kohli   109   55.0   6.0  8.0  198.18
8244     980969  V Kohli   108   58.0   8.0  7.0  186.21
15330   1359544  V Kohli   101   61.0  13.0  1.0  165.57
10929   1178410  V Kohli   100   58.0   9.0  4.0  172.41

In [60]:
deliveries[
    deliveries['striker']=="V Kohli"
].groupby('venue')[
    'runs_off_bat'
].sum().sort_values(
    ascending=False
)

venue
M Chinnaswamy Stadium                                                    1874
M.Chinnaswamy Stadium                                                     472
Wankhede Stadium                                                          400
M Chinnaswamy Stadium, Bengaluru                                          354
Feroz Shah Kotla                                                          335
Dubai International Cricket Stadium                                       333
Eden Gardens                                                              307
Rajiv Gandhi International Stadium, Uppal                                 298
Sharjah Cricket Stadium                                                   285
MA Chidambaram Stadium, Chepauk                                           285
Wankhede Stadium, Mumbai                                                  171
Saurashtra Cricket Association Stadium                                    164
Maharashtra Cricket Association Stadium                                   155
Sheikh Zayed Stadium                                                      155
Sawai Mansingh Stadium                                                    131
Rajiv Gandhi International Stadium, Uppal, Hyderabad                      100
Punjab Cricket Association Stadium, Mohali                                100
Arun Jaitley Stadium                                                       93
Maharashtra Cricket Association Stadium, Pune                              87
Brabourne Stadium, Mumbai                                                  78
Kingsmead                                                                  75
MA Chidambaram Stadium, Chepauk, Chennai                                   71
Punjab Cricket Association IS Bindra Stadium                               67
Sardar Patel Stadium, Motera                                               62
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh           59
JSCA International Stadium Complex                                         56
Arun Jaitley Stadium, Delhi                                                55
Shaheed Veer Narayan Singh International Stadium                           54
Narendra Modi Stadium, Ahmedabad                                           54
Dr DY Patil Sports Academy, Mumbai                                         54
St George's Park                                                           53
Newlands                                                                   53
Holkar Cricket Stadium                                                     48
Eden Gardens, Kolkata                                                      46
Rajiv Gandhi International Stadium                                         42
SuperSport Park                                                            34
Subrata Roy Sahara Stadium                                                 34
New Wanderers Stadium                                                      31
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow      31
Nehru Stadium                                                              23
Punjab Cricket Association IS Bindra Stadium, Mohali                       20
Sawai Mansingh Stadium, Jaipur                                             18
Brabourne Stadium                                                          17
Himachal Pradesh Cricket Association Stadium                               11
Zayed Cricket Stadium, Abu Dhabi                                           10
Dr DY Patil Sports Academy                                                  9
MA Chidambaram Stadium                                                      6
Vidarbha Cricket Association Stadium, Jamtha                                3
Name: runs_off_bat, dtype: int64

In [61]:
deliveries[
    deliveries['striker']=="V Kohli"
].groupby('bowling_team')[
    'runs_off_bat'
].sum()

bowling_team
Chennai Super Kings        985
Deccan Chargers            306
Delhi Capitals             269
Delhi Daredevils           761
Gujarat Lions              283
Gujarat Titans             232
Kings XI Punjab            681
Kochi Tuskers Kerala        50
Kolkata Knight Riders      861
Lucknow Super Giants       117
Mumbai Indians             857
Pune Warriors              128
Punjab Kings               180
Rajasthan Royals           618
Rising Pune Supergiant      83
Rising Pune Supergiants    188
Sunrisers Hyderabad        674
Name: runs_off_bat, dtype: int64

In [69]:
deliveries.groupby(
    ['season','venue','striker']
)['runs_off_bat'].sum()

season  venue                       striker
2008    Dr DY Patil Sports Academy  AB de Villiers     21
                                    AC Gilchrist      109
                                    AM Nayar           48
                                    AM Rahane           0
                                    CK Kapugedera       8
                                                     ...
2023    Wankhede Stadium, Mumbai    VR Iyer           104
                                    Vishnu Vinod       30
                                    Vivrant Sharma     69
                                    WP Saha             2
                                    YBK Jaiswal       124
Name: runs_off_bat, Length: 9469, dtype: int64

In [63]:
batter_stats.to_csv("batter_stats.csv")
season_batter_stats.to_csv("season_batter_stats.csv",index=False)
match_batter_stats.to_csv("match_batter_stats.csv",index=False)

In [64]:
# sab team-related purane columns hatao
match_batter_stats = match_batter_stats.drop(
    columns=[
        'innings',
        'batting_team',
        'bowling_team',
        'venue',
        'season'
    ],
    errors='ignore'
)

# innings + striker se actual mapping
temp = deliveries[
[
    'match_id',
    'innings',
    'striker',
    'batting_team',
    'bowling_team',
    'venue',
    'season'
]
].drop_duplicates()

# merge by match + striker
match_batter_stats = match_batter_stats.merge(
    temp,
    on=['match_id','striker'],
    how='left'
)

# duplicate remove
match_batter_stats = match_batter_stats.drop_duplicates(
subset=[
'match_id',
'striker',
'runs'
]
)

match_batter_stats.to_csv(
"match_batter_stats.csv",
index=False
)

In [65]:
match_batter_stats.to_csv(
    "match_batter_stats.csv",
    index=False
)

In [68]:
print(match_batter_stats.columns.tolist())

['match_id', 'striker', 'runs', 'balls', '4s', '6s', 'SR', 'innings', 'batting_team', 'bowling_team', 'venue', 'season']

In [67]:
batters = pd.DataFrame(
    {
        "player":sorted(
            deliveries['striker'].dropna().unique()
        )
    }
)

batters.to_csv(
    "all_batters.csv",
    index=False
)

print("saved")

saved

Bowling Stats

In [70]:
match_bowler_stats = deliveries.groupby(
    ['match_id','season','bowler',
     'batting_team','bowling_team',
     'venue']
).agg({

'runs_off_bat':'sum',
'ball':'count',
'player_dismissed':'count',
'wides':'sum',
'noballs':'sum'

}).reset_index()

In [71]:
match_bowler_stats.columns=[

'match_id',
'season',
'bowler',
'batting_team',
'bowling_team',
'venue',
'runs_conceded',
'balls',
'wickets',
'wides',
'noballs'

]

In [72]:
match_bowler_stats['runs_conceded']=(
match_bowler_stats['runs_conceded']
+
match_bowler_stats['wides'].fillna(0)
+
match_bowler_stats['noballs'].fillna(0)
)

In [80]:
match_bowler_stats['overs'] = (
    (match_bowler_stats['balls']//6)
    +
    ((match_bowler_stats['balls']%6)/10)
)

match_bowler_stats['SR'] = round(
    match_bowler_stats['balls']
    /
    match_bowler_stats['wickets'],2
)

match_bowler_stats['average'] = round(
    match_bowler_stats['runs_conceded']
    /
    match_bowler_stats['wickets'],2
)

match_bowler_stats = match_bowler_stats.replace(
    [float('inf')],
    0
)

match_bowler_stats['figures'] = (
    match_bowler_stats['wickets']
    .astype(int)
    .astype(str)
    +
    "/"
    +
    match_bowler_stats['runs_conceded']
    .astype(int)
    .astype(str)
)

match_bowler_stats.to_csv(
    "match_bowler_stats.csv",
    index=False
)

Season Wise Bowler Stats

In [81]:
season_bowler_stats = match_bowler_stats.groupby(
    ['season','bowler']
).agg({

    'runs_conceded':'sum',
    'balls':'sum',
    'wickets':'sum'

}).reset_index()

In [82]:
# overs
season_bowler_stats['overs']=(
    (season_bowler_stats['balls']//6)
    +
    ((season_bowler_stats['balls']%6)/10)
)

# economy
season_bowler_stats['economy']=round(
    season_bowler_stats['runs_conceded']
    /
    season_bowler_stats['overs'],
    2
)

# SR
season_bowler_stats['SR']=round(
    season_bowler_stats['balls']
    /
    season_bowler_stats['wickets'],
    2
)

# average
season_bowler_stats['average']=round(
    season_bowler_stats['runs_conceded']
    /
    season_bowler_stats['wickets'],
    2
)

season_bowler_stats=season_bowler_stats.replace(
    [float('inf')],
    0
)

In [83]:
season_bowler_stats.to_csv(
    "season_bowler_stats.csv",
    index=False
)

In [84]:
bowler_stats = match_bowler_stats.groupby(
    'bowler'
).agg({

    'runs_conceded':'sum',
    'balls':'sum',
    'wickets':'sum'

}).reset_index()

In [85]:
bowler_stats['overs']=(
    (bowler_stats['balls']//6)
    +
    ((bowler_stats['balls']%6)/10)
)

bowler_stats['economy']=round(
    bowler_stats['runs_conceded']
    /
    bowler_stats['overs'],
    2
)

bowler_stats['SR']=round(
    bowler_stats['balls']
    /
    bowler_stats['wickets'],
    2
)

bowler_stats['average']=round(
    bowler_stats['runs_conceded']
    /
    bowler_stats['wickets'],
    2
)

bowler_stats=bowler_stats.replace(
    [float('inf')],
    0
)

In [86]:
bowler_stats.to_csv(
    "bowler_stats.csv",
    index=False
)